### ISSUE TITLE
home logout btn navigation

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#103]
currently these btns exist on the home page. 

![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/c97f2897-ff4c-4e9f-b6c3-418788b129a7)

however, when clicking on home, it takes us into the home page we are in. This might be weird. 
When we go to the adventure page 

![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/083cb95b-c126-4efe-8403-d9fe0612c29d)

we see the links in the footer. When going back it takes us back to home, or we can logout. 

This issue *** 

![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/56a31e2c-a970-48e5-b68b-b08bef902738)

when in monster closet, we cannot navigate liike we could in the adventure page. 

we can handle this a few ways ;
1. just simply add the icons to the missing page. 
2. change the original position of the icons to the monster closet page and then the major operations can be done via closet. 
3. after a closet operation, we can useNavigate back to home page. 

these are just a few solutions I thought of, but these arent the only ones. We can discuss

**Comment by Rafflafressia** [comment]
We solved this issue. The monster closet did have the buttons rendered they're just at the bottom of the page and needs to be scrolled. 

I can conditionally render the home button. np
