### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/futuristic-wound#11]
git workflow presentation

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/5e16d775-5e4a-491e-9dcf-154b7a99f353)

**Comment by sbanati** [comment]
https://www.wrike.com/agile-guide/agile-development-life-cycle/


For AGILE details

**Comment by sbanati** [comment]
Git checkout -b feature-uc38-htmlhomeroutes
Git pull origin main
Code………..
Then git pull origin main
Then commit
Git status
Git add -A
Git commit -m “UC-38 created the following HTML home routes, GET home
page, GET dash…
…board, GET login, GET to create post, GET route to obtain post, comment by ID,
GET edit post by ID”
Send merge and pull request
