### ISSUE TITLE
utils/auth.js

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#19]
file should provide functionality for user authentication in a GraphQL server, including token verification middleware and token signing

**Comment by topcowmoo** [comment]
Created auth.js file. There are two screen shots to show the entire code but it is only file.



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/fe1ae582-6a05-4210-a943-0aac5562943a)



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/c6eb909c-11d2-4a80-8f54-551037a4b0b2)
