### ISSUE TITLE
Store cards component

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/futuristic-wound#23]
style choice for store cards

![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/a16f1435-7dee-410b-b706-c2165cd9bbb3)

**Comment by Rafflafressia** [comment]
Stripe Implementation video 

https://www.youtube.com/playlist?list=PLy1nL-pvL2M5xNIuNapwmABwEy2uifAlY

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/f047848e-dd3f-418c-9637-cbfbf78e84e5)

**Comment by sbanati** [comment]
when on the page of store , include the array of all mons , then event handler on button to get the monster, the id, then stripe operation on successful, then mutation to the user schema to save the monster

**Comment by sbanati** [comment]
https://github.com/topcowmoo/futuristic-wound/commit/18f7a23f1ef6182fe183ed28333704ad8feabb16
