### ISSUE TITLE
models/Monster.js

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#24]
setup the models for Monsters

**Comment by topcowmoo** [comment]
Created Monsters.js file and defined the schema for the monster. Thanks



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/e7c3f4f8-8dbb-40ed-8e55-1582dac4f8d5)

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/2a035932-e193-493f-8ecf-84df0f150cea)

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/0700d669-89c3-47ae-979a-b9b4fd481474)

**Comment by sbanati** [comment]
since we initialized schema and model, we dont need to include id as id will be give by nosql, monster._id

**Comment by topcowmoo** [comment]
I've removed monster_id 



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/5b5a85fe-006b-4b71-bda1-066781a9cca7)

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/4afc1a85-c40b-46ca-81e6-daeadf3c5334)
