### ISSUE TITLE
config/connection.js

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/futuristic-wound#3]
setting up mongoose to mongodb url in connection.js

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/f135cf19-95b1-4ebe-bf25-a5823f13816f)

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/61d7d065-360e-4c6c-9c15-77bc4be6282a)

**Comment by sbanati** [comment]
renamed database to baketomo
