### ISSUE TITLE
footer component

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#38]

**Comment by Rafflafressia** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149746567/28e377d7-107b-4fae-8001-419b92fd9856)

**Comment by Rafflafressia** [comment]
https://github.com/topcowmoo/futuristic-wound/pull/86

**Comment by Rafflafressia** [comment]
Updated Footer to include icons

[footer-fw-38](https://github.com/topcowmoo/futuristic-wound/pull/96)

**Comment by Rafflafressia** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149746567/3a2cf2c7-de2f-4515-94fe-fcd6eb9608d6)
