### ISSUE TITLE
Login page component

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#39]
Created Login page component. Added styling and logo assets.

**Comment by Rafflafressia** [comment]
Pull Request [login-component-fw-39](https://github.com/topcowmoo/futuristic-wound/tree/login-component-fw-39)

**Comment by Rafflafressia** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149746567/ea4c4ba8-bfff-40ed-b3f3-c280bfa146cf)
