### ISSUE TITLE
client/authjs

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#49]
auth.js for client side, this is the logic for the tokens i will put a screen shot for reference.

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/149584c8-b274-472c-ae3e-7061f3fc5ef6)

**Comment by topcowmoo** [comment]
created auth.js file



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/7e6ac02a-9879-4d72-a1f6-922d6641f5c1)



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149528212/1fc45639-e55e-4b3c-ac37-224a579144f3)
