### ISSUE TITLE
adventure mode

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/futuristic-wound#73]
Finished header, background and 2 buttons  for shop and dungeon, and finished footer. Reference HF-Mockup-adventure mode card

**Comment by Rafflafressia** [comment]
https://github.com/topcowmoo/futuristic-wound/pull/98



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149746567/36c49e04-6e3f-47ae-a7fc-b300f4cd6042)

**Comment by Rafflafressia** [comment]
Edited Footer as it affected the layout of the Adventure mode page, this will be applied to every page.
