### ISSUE TITLE
High fidelity mockup

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/futuristic-wound#9]
Create a high fidelity mockup to flesh out the functionality of the app.

Login Page
Signup Page
CrackPack Page
MyRoom Page
Battle Page
Store Page
Profile Page*** (Maybe)

**Comment by sbanati** [comment]
On top of this, maybe the design team should think / apply color theme / styling choices. When we make the login and signup functionality

the design team can either go in and make the required styling changes, or if we have them setup in advanced, the person making the functionality cna also do the styling aspect. 

The second way may be better as we have less people working on the same page

**Comment by sbanati** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/149754544/2326b738-e678-409d-9a55-3b971248086a)

**Comment by Rafflafressia** [comment]
Finished Mobile High Fidelity Mockup



![Image](https://github.com/topcowmoo/futuristic-wound/assets/149746567/74001f05-bd27-441e-b0a0-8fc3784235ae)

**Comment by F3N215** [comment]
![Image](https://github.com/topcowmoo/futuristic-wound/assets/150097577/cb6eb92e-2e98-4c1f-b0eb-fb1c46f7ea7f)
